Repository AtoLrn/projet_annuel_IW1, pull requests merged in 2022-07, with the labels that each got.

#79 fix(page): slugify update + redirect + dont call page if not needed
  www/Controller/Page.class.php
  www/Core/CleanWords.class.php
  www/Core/Interfaces/QueryBuilder.php
  www/Core/MysqlBuilder.class.php
  www/Core/Sql.class.php
  www/Model/Session.class.php
  www/View/back.tpl.php
  www/View/dynamic-page.view.php
  www/assets/img/logo/pages.php
  www/assets/src/js/dashboard.js
  www/index.php
Labels: bug, duplicate

#80 enh(admin): link from front to back session in tpl clean
  www/Core/MysqlBuilder.class.php
  www/Core/View.class.php
  www/View/back.tpl.php
  www/View/front.tpl.php
  www/assets/img/logo/home.php
  www/assets/src/js/pop-up.js
Labels: enhancement

#78 feature(user): pwd forget
  www/Controller/User.class.php
  www/Core/Mail.class.php
  www/Model/User.class.php
  www/View/modify-password.view.php
  www/View/pwd-forget.view.php
  www/View/register-login.view.php
  www/routes.yml
Labels: enhancement

#87 fix builder
  www/Core/MysqlBuilder.class.php
Labels: bug

#85 feature(user): modify profile info
  www/Controller/User.class.php
  www/Core/CleanWords.class.php
  www/Core/Mail.class.php
  www/Model/User.class.php
  www/View/mail-validation.view.php
  www/View/modify-email.view.php
  www/View/profile.view.php
  www/assets/src/js/profile.js
  www/conf.inc.json
  www/init.sql
  www/routes.yml
Labels: enhancement

#89 enh(comment): add design
  www/Controller/Article.class.php
  www/Model/Comment.class.php
  www/View/article.view.php
  www/errors.log
  www/routes.yml
Labels: enhancement

#90 enh: better stats + désactivate comment
  .gitignore
  www/Controller/Admin.class.php
  www/Controller/Article.class.php
  www/Model/Comment.class.php
  www/View/article.view.php
  www/View/dashboard.view.php
  www/assets/src/js/comment.js
  www/errors.log
Labels: enhancement

#95 enh(mail): clean template mail
  www/Core/Mail.class.php
  www/assets/src/scss/_globals.scss
Labels: enhancement

#96 fix(fail): xss + csrf
  www/Controller/Admin.class.php
  www/Controller/Article.class.php
  www/Controller/Category.class.php
  www/Controller/Certification.class.php
  www/Controller/Comment.class.php
  www/Controller/Ingredient.class.php
  www/Controller/Page.class.php
  www/Controller/Theme.class.php
  www/Controller/User.class.php
  www/Core/Middleware/Security.class.php
  www/Core/View.class.php
  www/Model/User.class.php
  www/View/Partial/form.partial.php
  www/View/article.view.php
  www/View/contact.view.php
  www/View/list-themes.view.php
  www/View/search-articles.view.php
  www/assets/src/js/article.js
  www/assets/src/js/certification.js
  www/assets/src/js/comment.js
  www/assets/src/js/dashboard.js
  www/assets/src/js/follow.js
  www/assets/src/js/ingredient.js
  www/assets/src/js/page.js
  www/assets/src/js/profile.js
  www/assets/src/js/user.js
Labels: bug

#97 fix csrf
  www/Core/View.class.php
  www/View/Partial/form.partial.php
  www/View/article.view.php
  www/View/list-themes.view.php
Labels: bug

#100 enh(article view): design + fix bug article backend
  www/Controller/Page.class.php
  www/View/article.view.php
  www/assets/src/js/article.js
  www/assets/src/scss/_globals.scss
  www/assets/src/scss/components/_articles.scss
Labels: enhancement

#91 feature(infra): add dynamic sitemap
  www/Controller/Page.class.php
  www/Core/SiteMapGenerator.class.php
  www/Model/Page.class.php
  www/errors.log
  www/sitemap.xml
Labels: enhancement

#106 enh(sql): replace all select
  www/Controller/Admin.class.php
  www/Controller/Article.class.php
  www/Controller/Category.class.php
  www/Controller/Certification.class.php
  www/Controller/Comment.class.php
  www/Controller/Ingredient.class.php
  www/Core/Sql.class.php
  www/Model/Article.class.php
  www/Model/Category.class.php
  www/Model/Theme.class.php
  www/View/article.view.php
  www/View/categories.view.php
  www/assets/img/logo/16d8fdfef086472154b02beb099b85824e297378-4f6ywv.png
  www/assets/src/js/certification.js
  www/assets/src/js/comment.js
  www/assets/src/js/ingredient.js
  www/errors.log
Labels: enhancement

#110 fix(pages): htmlspecialchar on content
  www/Controller/Page.class.php
  www/Core/SiteMapGenerator.class.php
  www/Model/Page.class.php
  www/assets/src/js/page.js
  www/errors.log
  www/sitemap.xml
Labels: bug
