Repository AtoLrn/projet_annuel_IW1, pull requests merged in 2022-02, with the labels that each got.

#16 :bug: fix(infra): Use token for $_SESSION
  www/Controller/Main.class.php
  www/Controller/User.class.php
Labels: bug

#19 fix(routes): fix route selection when a query is passed
  www/index.php
Labels: bug

#18 enh(auth): add auth engine
  www/index.php
  www/routes.yml
Labels: enhancement

#22 enh(auth): create auth middleware + multiSession
  init.sql
  www/Controller/User.class.php
  www/Core/Middleware/Security.class.php
  www/Model/Session.class.php
  www/Model/User.class.php
  www/conf.inc.php
  www/index.php
Labels: enhancement

#25 Features/list tables: select for left join, set-up list dashboard
  www/Controller/Admin.class.php
  www/Controller/User.class.php
  www/Core/Sql.class.php
  www/Model/User.class.php
  www/View/back.tpl.php
  www/View/list.view.php
  www/assets/css/dist/main.css
  www/assets/css/src/scss/_grid.scss
  www/assets/css/src/scss/components/_card.scss
  www/assets/css/src/scss/components/_image.scss
  www/assets/css/src/scss/components/_navbar.scss
  www/assets/css/src/scss/main.scss
  www/assets/css/src/scss/utils/_spacing.scss
  www/assets/img/users/antoine.svg
  www/assets/js/index.js
  www/routes.yml
Labels: enhancement, help wanted

#24 :bricks: conf(infra): singleton for Mail class
  www/Controller/User.class.php
  www/Core/Mail.class.php
Labels: enhancement

#30 enh(list): design aside card
  www/View/list.view.php
  www/assets/dist/main.css
  www/assets/dist/main.js
  www/assets/img/articles/article-pate.svg
  www/assets/img/logo/comments-white.svg
  www/assets/img/logo/like.svg
  www/assets/img/logo/star-white.svg
  www/assets/src/js/list.js
  www/assets/src/js/user.js
  www/assets/src/scss/_globals.scss
  www/assets/src/scss/_grid.scss
  www/assets/src/scss/_variables.scss
  www/assets/src/scss/components/_buttons.scss
  www/assets/src/scss/components/_list-tables.scss
  www/assets/src/scss/components/_pop-up.scss
  www/assets/src/scss/main.scss
  www/assets/src/scss/utils/_colors.scss
  www/assets/src/scss/utils/_spacing.scss
Labels: enhancement

#32 :lipstick:enh(login-register): same page for login register + css
  www/Controller/User.class.php
  www/Model/User.class.php
  www/View/Partial/form.partial.php
  www/View/front.tpl.php
  www/View/login.view.php
  www/View/register-login.view.php
  www/View/register.view.php
  www/assets/dist/main.css
  www/assets/dist/main.js
  www/assets/img/login-register-bg.png
  www/assets/src/js/register-login.js
  www/assets/src/scss/_globals.scss
  www/assets/src/scss/_grid.scss
  www/assets/src/scss/components/_buttons.scss
  www/assets/src/scss/components/_card.scss
  www/assets/src/scss/components/_login-register-selector.scss
  www/assets/src/scss/components/_navbar.scss
  www/assets/src/scss/components/_user-card.scss
  www/assets/src/scss/main.scss
  www/assets/src/scss/utils/_animation.scss
  www/assets/src/scss/utils/_spacing.scss
  www/assets/webpack/webpack.mix.js
  www/routes.yml
Labels: enhancement
